/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiAgentIdEventsRouteImport } from './routes/api/agent/$id/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIdEventsRoute = ApiAgentIdEventsRouteImport.update({
  id: '/api/agent/$id/events',
  path: '/api/agent/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/agent/$id/events': typeof ApiAgentIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/sessions' | '/api/agent/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sessions' | '/api/agent/$id/events'
  id: '__root__' | '/' | '/api/sessions' | '/api/agent/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiAgentIdEventsRoute: typeof ApiAgentIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$id/events': {
      id: '/api/agent/$id/events'
      path: '/api/agent/$id/events'
      fullPath: '/api/agent/$id/events'
      preLoaderRoute: typeof ApiAgentIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiAgentIdEventsRoute: ApiAgentIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
